version: "3.1"

services:
  db:
    container_name: mongodb-container
    image: mongo:latest
    restart: always
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=database
    ports:
      - 27017:27017